///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("fc7fa791-29fa-419d-b20b-cc60bb1d8543")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.GitRanorexAppFolder _gitranorex;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("fc7fa791-29fa-419d-b20b-cc60bb1d8543")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "fc7fa791-29fa-419d-b20b-cc60bb1d8543", ".\\RepositoryImages\\MyTest1Repositoryfc7fa791.rximgres")
        {
            _gitranorex = new MyTest1RepositoryFolders.GitRanorexAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("fc7fa791-29fa-419d-b20b-cc60bb1d8543")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GitRanorex folder.
        /// </summary>
        [RepositoryFolder("a7200a9f-2396-455a-b138-3e5bcd125f0f")]
        public virtual MyTest1RepositoryFolders.GitRanorexAppFolder GitRanorex
        {
            get { return _gitranorex; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The GitRanorexAppFolder folder.
        /// </summary>
        [RepositoryFolder("a7200a9f-2396-455a-b138-3e5bcd125f0f")]
        public partial class GitRanorexAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpswwwranorexcomrxmediarxuserInfo;

            /// <summary>
            /// Creates a new GitRanorex  folder.
            /// </summary>
            public GitRanorexAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GitRanorex", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "a7200a9f-2396-455a-b138-3e5bcd125f0f", "")
            {
                _httpswwwranorexcomrxmediarxuserInfo = new RepoItemInfo(this, "HttpsWwwRanorexComRxMediaRxUser", ".//div[#'et_builder_outer_content']/div/div/div[6]//img[@src='https://www.ranorex.com/rx-media/rx-user-guide/v8.3/E40/E4010-0000030.png']", 30000, null, "8a0c57d3-77bd-4a85-9a15-f91ae27eef78");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a7200a9f-2396-455a-b138-3e5bcd125f0f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a7200a9f-2396-455a-b138-3e5bcd125f0f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwRanorexComRxMediaRxUser item.
            /// </summary>
            [RepositoryItem("8a0c57d3-77bd-4a85-9a15-f91ae27eef78")]
            public virtual Ranorex.ImgTag HttpsWwwRanorexComRxMediaRxUser
            {
                get
                {
                    return _httpswwwranorexcomrxmediarxuserInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwRanorexComRxMediaRxUser item info.
            /// </summary>
            [RepositoryItemInfo("8a0c57d3-77bd-4a85-9a15-f91ae27eef78")]
            public virtual RepoItemInfo HttpsWwwRanorexComRxMediaRxUserInfo
            {
                get
                {
                    return _httpswwwranorexcomrxmediarxuserInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
